EXPERIMENT_CLASSES = ["Sampling_Experiments", "Fly-Through_Experiments", "Purging_Runs"]
MICS_SENSOR_TYPES = ['MiCS6814_NO2', 'MiCS6814_NH3', 'MiCS5524']
PID_SENSOR_TYPES = ['PID-sensor']
ALL_SENSOR_TYPES = MICS_SENSOR_TYPES + PID_SENSOR_TYPES
UPSTREAM_SENSOR_SPECIMEN = [('upstream', i) for i in range(2)]
LAYER_SENSOR_SPECIMEN = [('layers', i) for i in range(4)]
SENSOR_SPECIMEN = UPSTREAM_SENSOR_SPECIMEN + LAYER_SENSOR_SPECIMEN
DATASET_OUTPUT_PATH = 'dataset'
